/**
 * Renders a human-readable Computer System Validation report (Markdown) from a
 * generateValidation() result: chain statement, IQ/OQ/PQ result tables, the
 * Requirements Traceability Matrix, a qualification statement, and an approval
 * block for the operator's named reviewers to sign.
 */

const MARK = { PASS: "PASS", FAIL: "**FAIL**", NOT_APPLICABLE: "N/A" };

function table(headers, rows) {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return `${head}\n${sep}\n${body}`;
}

function stageTable(tests) {
  if (!tests || !tests.length) return "_No test cases in this stage._";
  return table(
    ["Test", "Title", "Expected", "Result", "Evidence (seq)"],
    tests.map((t) => [t.id, t.title, t.expected, MARK[t.result], t.citedSeqs.length ? t.citedSeqs.join(", ") : "—"]),
  );
}

export function renderReport(v, { generatedAt } = {}) {
  const chainLine = v.chain.verified
    ? `Chain **VERIFIED** — ${v.chain.count} events, head \`${v.chain.headHash}\`, key \`sha256:${v.chain.keyFingerprint}\`.`
    : `Chain **DID NOT VERIFY** — ${v.chain.reason}.`;

  const rtmRows = v.rtm.map((r) => [
    r.urs,
    r.ursText,
    r.fs.join(", ") || "—",
    r.tests.map((t) => `${t.id} (${MARK[t.result]})`).join("<br>") || "—",
    r.untested ? "not exercised" : r.covered ? "covered" : "**gap**",
  ]);

  const qualStatement = !v.chain.verified
    ? "**NOT QUALIFIED** — the audit chain did not verify; this report cannot be relied upon as validation evidence."
    : v.qualified
      ? "**QUALIFIED** — every executed test passed and every user requirement exercised by this run is covered, on a verified chain."
      : "**NOT QUALIFIED** — one or more executed tests failed or a user requirement is uncovered; see the matrix below.";

  return `# Validation Report — ${v.protocol.title}

| | |
|---|---|
| **Protocol** | \`${v.protocol.id}\` v${v.protocol.version} |
${generatedAt ? `| **Generated** | ${generatedAt} |\n` : ""}| **Audit chain** | ${chainLine} |
| **Outcome** | ${qualStatement} |

> This report is generated deterministically from a signed audit bundle: every
> result below is re-derived from recorded events and cites the audit \`seq\` it
> rests on. It is qualification evidence, not a certification; the operator
> confirms scope and signs below.

${!v.chain.verified ? "> ⚠️ **The chain did not verify. Do not rely on the results below.**\n\n" : ""}## 1. Installation Qualification (IQ)

${stageTable(v.stages.IQ)}

## 2. Operational Qualification (OQ)

${stageTable(v.stages.OQ)}

## 3. Performance Qualification (PQ)

${stageTable(v.stages.PQ)}

## 4. Requirements Traceability Matrix

${table(["URS", "Requirement", "FS", "Tests", "Coverage"], rtmRows)}

## 5. Summary

- Test cases: **${v.summary.total}** — ${v.summary.PASS} passed, ${v.summary.FAIL} failed, ${v.summary.NOT_APPLICABLE} not applicable.
- User requirements covered: **${v.summary.requirementsCovered} / ${v.summary.requirementsTotal}**.
- Qualification outcome: ${qualStatement}

## 6. Approval

The named reviewers below confirm the scope of this validation and accept the
results. (Maker-checker applies to the validation itself: the author and the
approver are different people.)

| Role | Name | Signature | Date |
|---|---|---|---|
| Prepared by (author) | | | |
| Reviewed by (QA) | | | |
| Approved by (system owner) | | | |

---

_Generated by \`@makerchecker/validation-kit\` from a signed Agent Action Proof
bundle. Re-verify the source bundle independently with \`@makerchecker/proof-verifier\`._
`;
}
